version: "2"

services:

  crawler:
    build: .
    entrypoint: scrapy crawl people_search
    volumes:
      - .:/opt/linkedin_scraper
    links:
      - splash
    environment:
      SCRAPY_USERNAME:
      SCRAPY_PASSWORD:
      SPLASH_ADDR: http://splash:8050

  splash:
    image: scrapinghub/splash
